package ch.hesge.ericMclaren.presentation;

import ch.hesge.ericMclaren.base.ArticleDao;
import ch.hesge.ericMclaren.domaine.Article;
import java.util.ArrayList;
import java.util.Collections;
import ch.hesge.ericMclaren.metier.Commande;

/**
 * Module 633.1-Programmation / TP P11
 *
 * Vente de matériel de ski
 *
 * Fenêtre principale de l'application
 *
 * @author Eric
 */
public class MainFrm extends java.awt.Frame {

    ArrayList listeArticles;
    ArrayList listeCommandes = new ArrayList();
    
    private static final String COMMANDES = "Commandes.txt";

    /**
     * Constructeur - Initialisation des composants de la fenêtre - nomF : nom
     * du fichier de données
     *
     * @param nomF
     */
    public MainFrm(String nomF) {
        initComponents();
        lblMonnaie.setText(Article.MONNAIE);
        listeArticles = ArticleDao.getListeArticles(nomF);
        Collections.sort(listeArticles);
        remplirArticles();
    } // MainFrm

    /* Remplie la liste d'articles au chargement de la fenêtre */
    private void remplirArticles() {
        for (int i = 0; i < listeArticles.size(); i++) {
            lstArticles.add(((Article) listeArticles.get(i)).toString());
        }
    } // remplirArticles

    /* Ajoute les articles dans la liste des commandes */
    private void ajouterArticles() {
        int[] indicesArticles = lstArticles.getSelectedIndexes();
        for (int i = 0; i < indicesArticles.length; i++) {
            Article article = (Article) listeArticles.get(indicesArticles[i]);
            int indice = listeCommandes.indexOf(new Commande(article, 0));
            if (indice == -1) {
                listeCommandes.add(new Commande(article, 1));
            } else {
                ((Commande) listeCommandes.get(indice)).incQte(1);
            }
        }
        miseAJourCommandes();
    } // ajouterArticles

    /* Supprime les commandes selectionnées */
    private void supprimerCommandes() {
        int[] indicesCommandes = lstCommandes.getSelectedIndexes();
        for (int i = indicesCommandes.length - 1; i >= 0; i--) {
            listeCommandes.remove(indicesCommandes[i]);
        }
        miseAJourCommandes();
    } // supprimerCommandes

    /* Met à jour la nouvelle liste de commandes */
    private void miseAJourCommandes() {
        lstCommandes.removeAll();
        for (int i = 0; i < listeCommandes.size(); i++) {
            lstCommandes.add(((Commande) listeCommandes.get(i)).toString());
        }
        miseAJourCompteurs();
    } // miseAJourCommandes

    /* Met à jour les compteurs pour le total de la commande et le nombre d'articles */
    private void miseAJourCompteurs() {
        int nbArticles = 0;
        double totalCommande = 0.0;
        for (int i = 0; i < listeCommandes.size(); i++) {
            Commande commande = (Commande) listeCommandes.get(i);
            double prix = ((Article) commande.getArticle()).getPrix();
            totalCommande += (prix * commande.getQte());
            nbArticles += commande.getQte();
        }
        tfNbArticles.setText(nbArticles + "");
        tfTotalCommande.setText(totalCommande + "");
    } // miseAJourCompteurs

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label4 = new java.awt.Label();
        lstArticles = new java.awt.List();
        btnAjouterCommande = new java.awt.Button();
        label6 = new java.awt.Label();
        lstCommandes = new java.awt.List();
        btnSupprimerCommande = new java.awt.Button();
        label7 = new java.awt.Label();
        tfTotalCommande = new java.awt.TextField();
        lblMonnaie = new java.awt.Label();
        label8 = new java.awt.Label();
        tfNbArticles = new java.awt.TextField();
        label2 = new java.awt.Label();

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        label4.setText("Articles");

        lstArticles.setMultipleMode(true);
        lstArticles.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lstArticlesItemStateChanged(evt);
            }
        });

        btnAjouterCommande.setEnabled(false);
        btnAjouterCommande.setLabel("Ajouter � la commande");
        btnAjouterCommande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterCommandeActionPerformed(evt);
            }
        });

        label6.setText("Commande");

        lstCommandes.setMultipleMode(true);
        lstCommandes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lstCommandesItemStateChanged(evt);
            }
        });

        btnSupprimerCommande.setEnabled(false);
        btnSupprimerCommande.setLabel("Retirer de la commande");
        btnSupprimerCommande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerCommandeActionPerformed(evt);
            }
        });

        label7.setText("TOTAL COMMANDE");

        tfTotalCommande.setEditable(false);

        lblMonnaie.setText("monnaie");

        label8.setText("NOMBRE ARTICLES");

        tfNbArticles.setEditable(false);

        label2.setText("articles");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfTotalCommande, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMonnaie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfNbArticles, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lstArticles, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAjouterCommande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSupprimerCommande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lstCommandes, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lstArticles, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lstCommandes, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSupprimerCommande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAjouterCommande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfTotalCommande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMonnaie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNbArticles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /* Fin de l'application */
  private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      dispose();
  }//GEN-LAST:event_formWindowClosing

  private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
      System.exit(0);
  }//GEN-LAST:event_formWindowClosed

    private void btnAjouterCommandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterCommandeActionPerformed
        ajouterArticles();
        lstArticles.deselect(lstArticles.getSelectedIndex());
        btnAjouterCommande.setEnabled(false);
    }//GEN-LAST:event_btnAjouterCommandeActionPerformed

    private void lstArticlesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lstArticlesItemStateChanged
        btnAjouterCommande.setEnabled(lstArticles.getSelectedIndexes().length > 0);
    }//GEN-LAST:event_lstArticlesItemStateChanged

    private void lstCommandesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lstCommandesItemStateChanged
        btnSupprimerCommande.setEnabled(lstCommandes.getSelectedIndexes().length > 0);
    }//GEN-LAST:event_lstCommandesItemStateChanged

    private void btnSupprimerCommandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerCommandeActionPerformed
        supprimerCommandes();
        btnSupprimerCommande.setEnabled(false);
    }//GEN-LAST:event_btnSupprimerCommandeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnAjouterCommande;
    private java.awt.Button btnSupprimerCommande;
    private java.awt.Label label2;
    private java.awt.Label label4;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label lblMonnaie;
    private java.awt.List lstArticles;
    private java.awt.List lstCommandes;
    private java.awt.TextField tfNbArticles;
    private java.awt.TextField tfTotalCommande;
    // End of variables declaration//GEN-END:variables

} // MainFrm
